run:
  timeout: 5m
linters-settings:
  nlreturn:
    block-size: 3

  godot:
    scope: declarations

  gofumpt:
    module-path: avito-tenders
    extra-rules: true

  goimports:
    local-prefixes: avito-tenders

linters:
  fast: false
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - forcetypeassert
    - goconst
    - gocritic
    - godot
    - gofmt
    - gofumpt
    - goimports
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosimple
    - govet
    - importas
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nilerr
    - nlreturn
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
