services:
  webserver:
    container_name: "avito-webserver"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  postgres:
    container_name: "avito-postgres"
    image: postgres:16.2
    env_file:
      - .env.docker
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql-avito-tenders/data

volumes:
  pgdata: {}